FROM docker.elastic.co/elasticsearch/elasticsearch:8.4.3

USER root

USER elasticsearch

RUN /usr/share/elasticsearch/bin/elasticsearch-plugin install pl.allegro.tech.elasticsearch.plugin:elasticsearch-analysis-morfologik:8.4.3
